name: Build and deploy package

on: 
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Test
        run: dotnet test
        
      - name: Create the package
        run: dotnet pack --configuration Release
    
